### ISSUE TITLE
Editor scroll bar misaligned under 'Background' tab.

### ISSUE THREAD

**Issue by Re4XN** [fh-fvtt/zweihander#112]
The editor's scroll bar is misaligned if the text within overflows the container:

![image](https://user-images.githubusercontent.com/16267371/155239465-1ae6e91b-5c95-47f4-a849-a9ef2b71aa48.png)

A possible improvement, removing `overflow-y: scroll` from `.sheet .editor-content` and instead adding this rule to the `div` that contains the title and the editor:

![image](https://user-images.githubusercontent.com/16267371/155239373-c7d030b1-3787-4db1-9045-ca61463e0a8f.png)

**Comment by kvndrsslr** [comment]
Yea I have found no good solution for this yet. Doing it like you suggested would mean the editor controls get scrolled, which is not ideal. I'd rather live with the visual quirk until I upgrade my CSS Fu ^^. Will have a look again, but not high prio for me

**Comment by Re4XN** [comment]
> Doing it like you suggested would mean the editor controls get scrolled, which is not ideal.

You mean there will be two scrollbars? Yeah, it's kinda odd, unfortunately. I remember I suggested a while back we could use a different editor instead of the default Foundry one, such as [Pen Editor](https://github.com/sofish/pen). I can start looking into that.

**Comment by kvndrsslr** [comment]
I have just spent an hour this morning styling the default editor properly xD. But I guess it's not in vain, as it is used in other places.
