### ISSUE TITLE
Add a 'Recuperation Time' field to Injuries.

### ISSUE THREAD

**Issue by Re4XN** [fh-fvtt/zweihander#120]
![image](https://user-images.githubusercontent.com/16267371/159021472-8288709a-eef3-4dd4-ba22-55743754d913.png)

Injuries have a set Recuperation time associated with them. This information is currently missing both on the Injury `Item` and on the `Actor` sheet. This roll should automatically be made when the Injury is dragged to the sheet.

**Comment by kvndrsslr** [comment]
done
