### ISSUE TITLE
Allow the embedding of inline rolls in Item descriptions.

### ISSUE THREAD

**Issue by Re4XN** [fh-fvtt/zweihander#124]
Journal Entries currently allow for the following:

![image](https://user-images.githubusercontent.com/16267371/159489648-fbea88c1-64a9-4d05-9198-097eecf4b91f.png)

It would be great if the same functionality could be implemented for spells and rituals (and other relevant `Item`s), e.g.:

![image](https://user-images.githubusercontent.com/16267371/159489775-986bd09e-2016-4dc5-b0ce-dfcbba61b68f.png)

**Comment by kvndrsslr** [comment]
Currently works at some places in item descriptions. will be completed together with the `rules` schema changes.
Should also work in the chat item cards.

**Comment by Re4XN** [comment]
Replacement complete for Spells and Rituals.

**Comment by kvndrsslr** [comment]
Should work in all places, reopen if it's missing anywhere
