### ISSUE TITLE
Add an option to the Actor Configuration menu to allow Chaos to manifest on faces other than 6.

### ISSUE THREAD

**Issue by Re4XN** [fh-fvtt/zweihander#128]
The Cruel Tutelage Talent (Hedgewise and Cultist, CRB) says Chaos Manifestations are invoked on face 1 or 6. An option to account for this, on an `Actor` by `Actor` basis, should be implemented.

**Comment by kvndrsslr** [comment]
This could also be implemented as an active effect type (better automation).

**Comment by Re4XN** [comment]
> This could also be implemented as an active effect type (better automation).
This basically goes back to the discussion we had about what should and shouldn't be an AE 😛 When the the time comes to start implementing them, we should probably get together in a call or something to iron out a definition we're comfortable with. I'll open an issue for it.
