### ISSUE TITLE
Add an 'Effect' field to Trappings.

### ISSUE THREAD

**Issue by Re4XN** [fh-fvtt/zweihander#129]
Certain `Item`s have an associated effect, e.g. poisons, magickal trappings, talismans, etc... Having an 'Effect' field available to write down these mechanics would be helpful, as the 'Description' field that is currently available is intended for fluff text.

![image](https://user-images.githubusercontent.com/16267371/160191812-6ce61b8a-56d2-42ff-82d6-0d13fb4759c4.png)

**Comment by kvndrsslr** [comment]
Done
