### ISSUE TITLE
Limit Actor sheet visibility when permissions are configured to 'Limited' or 'Observer'.

### ISSUE THREAD

**Issue by Re4XN** [fh-fvtt/zweihander#130]
Currently, both 'Limited' and 'Observer' behave as 'Observer', i.e. everything on the sheet is visible but the viewer cannot interact with it. The behavior for 'Limited' should be changed to hide nearly everything concerning a character:

![image](https://user-images.githubusercontent.com/16267371/160194362-75d56564-cfc4-491a-b181-f9d8e6b7185e.png)

**Comment by kvndrsslr** [comment]
- character sheets mostly done (need to hide more stuff)
- npc/ creature sheets in work
![image](https://user-images.githubusercontent.com/46481738/160238677-add9d1ee-1f5b-4bfb-9dd0-24098768c65e.png)
