### ISSUE TITLE
Implement global Corruption Tracker application

### ISSUE THREAD

**Issue by Re4XN** [fh-fvtt/zweihander#151]
A way to track each character's Corruption (and reasons for it) would be incredibly useful as opposed to e.g. writing it down on a Journal entry. It would _probably_ need to be implemented with recourse to `socketlib` because each connected player's Corruption value needs to be displayed and can be modified by the player (on their sheet) or the GM (through this app).

Needs further discussion.

**Comment by kvndrsslr** [comment]
Since we now have Journals v2 I would say tracking it in a journal is good enough. If you want to have it a certain design / UI there's now lots of new APIs for creating custom JournalEntrySheet / JournalPageSheet, but I'm not sure if it's worth the time

**Comment by Re4XN** [comment]
Agreed. Can be closed IMO.

**Comment by kvndrsslr** [comment]
Done & done :)
