### ISSUE TITLE
Add license to the system repository

### ISSUE THREAD

**Issue by Re4XN** [fh-fvtt/zweihander#157]
We need to figure out the license we want to go with.

**Comment by kvndrsslr** [comment]
I think its fine to go with MIT, which if I remember is your preferred one. We should also include the following paragraph.

> This game system is powered by ZWEIHÄNDER Grim & Perilous RPG ™, a trademark of Grim & Perilous Studios LLC, in the USA and other countries. Used with permission.  Original text content of ZWEIHÄNDER Grim & Perilous RPG is licensed under a Creative Commons Attribution-Noncommercial-Share Alike 3.0 Unported License. ZWEIHÄNDER Logo, content and original artwork are copyright © 2009–2018, Grim & Perilous Studios, LLC unless otherwise specified.
