### ISSUE TITLE
Seemingly no way to Modify Global Modifiers for Damage and Peril Thresholds.

### ISSUE THREAD

**Issue by yig1015** [fh-fvtt/zweihander#161]
I know you can simulate Physical with armor but Mental has no equivalent. This is a common thing that needs modified due to several Professional Traits.

**Comment by Re4XN** [comment]
This will come with the integration of Active Effects, the next major update to the system.

**Comment by Re4XN** [comment]
Implemented in `dev`, will make its way to stable eventually.
