### ISSUE TITLE
description field disappears after changing icon

### ISSUE THREAD

**Issue by Verencius** [fh-fvtt/zweihander#169]
**Describe the bug**

**To Reproduce**
1. create description
2. change icon
3. description is empty

**Expected behavior**
Description field stays filled

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Behavior Checked on:
traits
trappings
professions
weapons

**Comment by kvndrsslr** [comment]
Closed as not reproducable
