### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by StormDarkwood** [fh-fvtt/zweihander#174]
The localization file (/lang/en.json) includes very few words that can be translated. Apart from character type, item type, status effects and difficulties the rest of the system cannot be translated.

It would be nice if the localization file could be as large as possible to be able to translate the whole character sheet and other components of the system. 

The game is coming out soon in both Spanish and French and it would help the community a lot.

Best regards

![Screenshot_1](https://user-images.githubusercontent.com/75157840/205495644-c39de8fb-f0c8-4687-80c7-d18132467972.png)
![Screenshot_2](https://user-images.githubusercontent.com/75157840/205495648-eb280897-f696-4c88-86ab-64705bf4cded.png)
![Screenshot_3](https://user-images.githubusercontent.com/75157840/205495652-e7cec918-c39a-49dc-88f4-705390085c5b.png)

**Comment by Re4XN** [comment]
Related to https://github.com/fh-fvtt/zweihander/issues/90.

**Comment by kvndrsslr** [comment]
Closing in favor of #90
