### ISSUE TITLE
Spanish Language Support

### ISSUE THREAD

**Issue by kvndrsslr** [fh-fvtt/zweihander#178]
- [x] Release beta version
- [x] Clean up keys
- [x] Collect missing keys from test users

**Comment by kvndrsslr** [comment]
Please leave comments here for missing spanish translations!

**Comment by lozanoje** [comment]
Clean up keys task completed: https://github.com/fh-fvtt/zweihander/pull/180

**Comment by lozanoje** [comment]
Step 3 of the project I think is already done with: https://github.com/fh-fvtt/zweihander/pull/181

Now bugfixes, I think this issue can stay opened in case someone reports something related to localization

**Comment by Re4XN** [comment]
Closing. Issues with translations can be reported over at the Discord.
