### ISSUE TITLE
The Beta update screws with custom skills

### ISSUE THREAD

**Issue by Nexusflamehart** [fh-fvtt/zweihander#179]
**Describe the bug**
After installing the Beta Update, the custom skill list I set up now reads out the codewise name for the skills as opposed to just saying the name. For example

**To Reproduce**
1. Open Character Sheet with Custom Skill List
2. Look for the names of any unique skills

**Expected behavior**
The skill list should have a list of 1 - 2 word skill names and an indication of what skill they reference in brackets

**Screenshots**
https://i.imgur.com/KbFrWUg.png
https://i.imgur.com/egjoW3D.png

**Desktop (please complete the following information):**
 - OS: Window 10
 - Browser: Chrome
 - Version: 5.0.5 - Beta 3

**Comment by lozanoje** [comment]
This is because of the localization project, I will try to get rid of this problem

**Comment by Re4XN** [comment]
I think the easiest solution would be to somehow exclude custom skills from being subject to localization. If you're homebrewing custom stuff, you can do it in your native language, you don't need the system itself to be doing any extra work.

**Comment by lozanoje** [comment]
> I think the easiest solution would be to somehow exclude custom skills from being subject to localization. If you're homebrewing custom stuff, you can do it in your native language, you don't need the system itself to be doing any extra work.

Yes, this is what I think also, i will incorporate the fix in my opened PR for beta4 later on.

**Comment by lozanoje** [comment]
Fixed at my last commit: https://github.com/fh-fvtt/zweihander/pull/180/commits/e015d87bdc6dd3570aeb79a30e1884c90e7881b8
