### ISSUE TITLE
Error dragging anything to character sheet

### ISSUE THREAD

**Issue by lordwey** [fh-fvtt/zweihander#205]
![image](https://github.com/fh-fvtt/zweihander/assets/34535551/3979fbb0-442b-46b2-bd99-093a32705889)

**Comment by lordwey** [comment]
![image](https://github.com/fh-fvtt/zweihander/assets/34535551/d3b91cbb-3350-4758-ad7f-8b4c9e31ebc6)

**Comment by Re4XN** [comment]
Without any further description (examples of which are thoroughly detailed in the [bug report submission form](https://github.com/fh-fvtt/zweihander/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=), there's nothing to go off of for us to fix this.

Tested on the latest version of FoundryVTT (11.309), in a new world with no modules and cannot reproduce. Closing.
