### ISSUE TITLE
System setting to select which table to roll for diferent injuries

### ISSUE THREAD

**Issue by lozanoje** [fh-fvtt/zweihander#211]
To allow localization of injury tables

**Comment by lozanoje** [comment]
No need to set a system setting, I sorted out searching for all tables in currrent compendia for gm-tables, implemented here:

https://github.com/fh-fvtt/zweihander/pull/212/commits/ad95bc5326c7f6b5d6adf94885ffa4eac3a4395f

**Comment by lozalojo** [comment]
Fixed: https://github.com/fh-fvtt/zweihander/pull/212

**Comment by lozanoje** [comment]
Fixed: https://github.com/fh-fvtt/zweihander/pull/212
