### ISSUE TITLE
Weapon Damage Formula

### ISSUE THREAD

**Issue by SuperbHaggis** [fh-fvtt/zweihander#75]
When rolling damage, the final result doesn't include the Bonus. The tooltip shows:

`0[Combat Bonus] + 1 + 1d6x6 = 0 + 1 + 2`

On the item itself, the formula looks like (using Flintlock Pistol as an example):

`[CB] + 1 + (1+[#])d6x6 + [ Bonus]` **Note the space before 'Bonus'**

Could this be an issue with `abbreviations2DataPath` in `module/utils.js` not correctly determining the Bonus? For example, is the damage supposed to calculate with [CB] instead of [Combat Bonus]?

**Comment by Re4XN** [comment]
The `[ Bonus]` text part is a relic of an older version and should be removed. I can guarantee `abbreviations2DataPath` is working correctly, the problem appears to be the fact that the data path generated, e.g. `@stats.primaryAttributes.combat.bonus` is completely ignored when rolling. Thanks for pointing it out!

**Comment by kvndrsslr** [comment]
Sorry, I introduced this bug with yesterdays release. Been a while since I've interacted with Foundry API, forgot that `.toObject()` does not carry derived properties (like the bonus). `.toObject(false)` is the way. 👍🏼
