### ISSUE TITLE
Add the ability to randomly roll an Injury, Disease or Disorder.

### ISSUE THREAD

**Issue by kvndrsslr** [fh-fvtt/zweihander#79]
*Originally created by @ghost (https://github.com/fh-fvtt/zweihander/issues/39):*

https://trello.com/c/YG5XSIHi/38-add-the-ability-to-randomly-roll-an-injury-disease-or-disorder

Zweihänder rules often times rely on tables to randomly assign an Injury, Disease or Disorder. Adding a button that would emulate this process on the `Actor` sheet would be a nice QoL feature to swiften play.

**Comment by kvndrsslr** [comment]
I'm curretnly adding Roll Tables to the compendium and I'm sure there are modules that allow people to bind these to macros if they wish so.
Would that satisfy what you had in mind @Re4XN ?

**Comment by Re4XN** [comment]
My original intent had been to put a button on the sheet, but after playing in a system where injuries are commonplace (Forbidden Lands), I don't think such a button would get much use. The usual workflow is: GM rolls injury, Player drags injury from chat onto their sheet.

So I'm fine with leaving the actual generation to the tables and custom macros.
