### ISSUE TITLE
Implement currency exchange calculator.

### ISSUE THREAD

**Issue by kvndrsslr** [fh-fvtt/zweihander#83]
*Originally created by @ghost (https://github.com/fh-fvtt/zweihander/issues/43):*

https://trello.com/c/oWFRBehh/9-implement-currency-exchange-calculator

A simple calculator accessible through a button on the 'Trappings' page that would allow a player to convert their currency between brass, silver and gold.

**Comment by heretyk999** [comment]
I have implemented simple currency exchange in the form of additional buttons between currencies. When left-clicked, it exchanges from bigger to smaller currency, while right-click does the opposite.
![zweihander-money-exchange](https://user-images.githubusercontent.com/26313554/229358184-40c36937-211a-49e5-8bf4-163a5c559059.png)

You can check it on "money-exchange" branch: https://github.com/heretyk999/zweihander/tree/money-exchange
A little later I can create a pull request for it.
