### ISSUE TITLE
Add support for Macro Bar drag & drop.

### ISSUE THREAD

**Issue by kvndrsslr** [fh-fvtt/zweihander#84]
*Originally created by @ghost (https://github.com/fh-fvtt/zweihander/issues/44):*

https://trello.com/c/EJEAAGdP/78-add-support-for-macro-bar-drag-drop

Implementing this feature would allow players to e.g. drag their favored weapon attack to the Macro Bar for quick access, allowing them to make certain rolls without opening the character sheet, thus speeding up play.

**Comment by kvndrsslr** [comment]
https://foundryvtt.wiki/en/development/guides/SD-tutorial/SD16-Adding-macrobar-support-to-your-Items

**Comment by Re4XN** [comment]
Implemented for Weapons and Spells.
