### ISSUE TITLE
Implement permanent warnings on the actor sheet

### ISSUE THREAD

**Issue by kvndrsslr** [fh-fvtt/zweihander#87]
*Originally created by @ghost (https://github.com/fh-fvtt/zweihander/issues/47):*

https://trello.com/c/lgzfJrw8/92-automatically-prompt-the-user-to-manually-change-a-profession-item-when-it-has-the-same-talents-as-a-previous-profession

When a Profession has the same Talent as another from a lower tier, the player and GM are supposed to work together to come to a consensus in replacing it with something else. In order to avoid weird behavior, we should either:

1) Automatically delete a Talent from a Profession `Item` when we detect the presence of the same Talent in a previous tier.
2) Automatically prompt the player to change the list of Talents for that Profession `Item`.

**Comment by kvndrsslr** [comment]
Currently, the system notifies the user *once* after adding or editing a profession with the same talent(s) as a previous one.
There should be at least some sort of permanent reminder directly on the sheet in order to resolve this issue.

**Comment by Re4XN** [comment]
Duplicate/misspelled Talents are highlighted on the sheet and a permanent danger icon appears next to the Profession, prompting the user to change the Talent list.
