### ISSUE TITLE
Implement Active Effect concept

### ISSUE THREAD

**Issue by kvndrsslr** [fh-fvtt/zweihander#89]
*Originally created by @ghost (https://github.com/fh-fvtt/zweihander/issues/49):*

https://trello.com/c/MmDvJV5w/66-integrate-active-effects-into-the-system

A lot of `Item`s should be able to modify an `Actor`'s stats, e.g. a Spell modifying Initiative. For this purpose, Active Effects should be used.

**Comment by Re4XN** [comment]
Depends on https://github.com/fh-fvtt/zweihander/issues/171
