### ISSUE TITLE
Editing an Item's description breaks formatting on the Actor sheet.

### ISSUE THREAD

**Issue by kvndrsslr** [fh-fvtt/zweihander#99]
*Originally created by @ghost (https://github.com/fh-fvtt/zweihander/issues/60):*

https://trello.com/c/xn9JqZrw/102-editing-an-items-description-breaks-formatting-on-the-actor-sheet

When a description is edited (e.g. a Trait's effect), the formatting on the character sheet breaks.

**Comment by Re4XN** [comment]
Fixed.
